### ISSUE TITLE
Variable number of placeholders

### ISSUE THREAD

**Issue by laurentpsychedelic** [capitaomorte/yasnippet#348]
Hello,

First, thank you for your great work on yasnippet,
I was wondering if there is a way to define snippet with a variable number of placeholders, which number would be defined when expanding the snippet, not statically when defining it.

For example, let's say I want to define a snippet for a Java enumeration with a variable number of elements. I want to use the same snippet to expand an enumeration with, say, 3 elements, that the one used to expand to four elements (without having to define as many snippets as the number of possibilities for the number of elements I want to use, like enum1.yasnippet, enum2.yasnippet, ..., enumN.yasnippet etc.):

``` java
public enum MyEnum {
    ELE1, ELE2, ELE3
}
```

``` java
public enum MyEnum {
    ELE1, ELE2, ELE3, ELE4
}
```

Is there a way to request a number from the user (here it will be "3" for the first example, "4" for the second) and then using it for a variable number of placeholders?

I am sorry if my question is too basic or, on the contrary, completely out of the scope of what is possible with yasnippet.

Thank you !

**Comment by Dav1d23** [comment]
I'm really sorry to resume this old thread, but I could not find anything else on any tutorial.
I would like to use a placeholder to create a multiline, placeholder rich template. In practice, 

I would like to have something like this
```
# -*- mode: snippet -*-
# name: split
# key: split
# --

${1:$(format "%s" (mapconcat (lambda (arg) (format "// param %s <placeholder>\n" arg)) (seq-map 's-trim (s-split "," yas-text))))}
function(${1:args}) {
    $0
}
```
that creates (right now)
```
// param 1 <placeholder>
// param 2 <placeholder>
// param 3 <placeholder>

function(1, 2, 3) {
  
}
```
where, instead of <placeholder>, I have an "actual" placeholder I can "tab" into. The solution provided here seems to be to have a separate step where I read the function signature, I do the split, and then I generate the template I need.

Is there another way to do that?

(as a side question: how can I make the transformation less ugly? is there a way to embed lisp functions inside the templates without resorting to the "command" type?)

**Comment by monnier** [comment]
> where, instead of <placeholder>, I have an "actual" placeholder I can "tab"
> into. The solution provided here seems to be to have a separate step where
> I read the function signature, I do the split, and then I generate the
> template I need.
>
> Is there another way to do that?

The `snippet-engine` branch would likely be a good solution, if someone
was motivated enough to finish it.
