### ISSUE TITLE
`yas-wrap-around-region` could use the kill ring

### ISSUE THREAD

**Issue by feicunrain** [capitaomorte/yasnippet#374]
Yas is documented than other open-source code,thx : ) but seems it is not enough. I read all tutorial but cann't figure out how to use it.

Because in my system(Xubuntu ,3.5.0-26 kernel,emacs ver 24.1 installed from apt) , when you select a region, then you type sth, the region is not deleted.  the text is no longer selected, new content appear after the cursor...

So I can't use "yas-wrap-around-region"，（I set it to 'cua）.how can i get it worked

I try "C-k",but it is seems not use the kill-ring.

**Comment by npostavs** [comment]
I don't think it makes sense to just use the kill ring, because there is almost always *something* in the kill-ring, and often you would not want that inserted into the snippet expansion.

I think instead it would make sense to allow using a register outside of `cua-mode`, like so: https://github.com/capitaomorte/yasnippet/compare/master...npostavs:wrap-around-region

And probably this should be explained in the manual somewhere, though I'm not sure where it would go.
