### ISSUE TITLE
Strange kill word behavior after expansion

### ISSUE THREAD

**Issue by snosov1** [capitaomorte/yasnippet#515]
I have the following snippet for cc-mode:

    # -*- mode: snippet -*-
    # name: for
    # key: for
    # --
    for (${1:size_t i = 0}; ${2:i < N}; ${3:i++})
    {
        $0
    }

And I observe the following erroneous and strange behavior:
1) I print `for` and hit tab, so that the snippet is expanded and I'm about to edit the $1 field (which is everything between `(` and first `;`. This text is, obviously, overlaid by yasnippet.
2) I want to delete `size_t`, so I hit `M-d` to execute `kill-word`. I expect it to kill the text `size`, but instead, it kills everything up to the `<` symbol, so the line looks as follows: `for (< N; i++)` with the cursor just before the `<` symbol. Obviously, there are no overlays left since I've removed all the overlaid text.
3) Then I hit `C-/` to perform an undo and I'm back to exactly the same state as in item 1), i.e. the line is `for (size_t i = 0; i < N; i++)`, the cursor is right before the symbol `s` and the text `size_t i = 0` is overlaid.
4) But surprisingly, if I do kill-word again, this time it does exactly what it should - the line becomes `for (_t i = 0; i < N; i++)`, the cursor is before the `_` symbol and the text `_t i = 0` is overlaid.

This issue is easily reproduced with both "GNU Emacs 24.3.1" and "GNU Emacs 24.3.93.1" with `-Q` flag. Yasnippet version from MELPA - `yasnippet-20140821.38`.

**Comment by npostavs** [comment]
The reason this is happening is because of `yas--on-field-overlay-modification`. As promised in the docstring, it clears the field if point is it at the field start and the field is not modified (which explains why this doesn't happen after undoing and trying again). Since the clearing happens *before* (i.e. `(not after?)`) the change, the `delete-word` finishes by deleting characters following the field.

Similar problems can be seen with other deletion or modification commands if they are executed with point at field start (e.g. `C-t`).

I think #639 should fix it.

```elisp
(defun yas--on-field-overlay-modification (overlay after? _beg _end &optional _length)
  "Clears the field and updates mirrors, conditionally.

Only clears the field if it hasn't been modified and it point it
at field start.  This hook doesn't do anything if an undo is in
progress."
  ...
             (when (and (not after?)
                        (not (yas--field-modified-p field))
                        (eq (point) ... (yas--field-start field))))
               (yas--skip-and-clear field))
             (setf (yas--field-modified-p field) t))))))
```

**Comment by snosov1** [comment]
Just tried it. It seems to work!
