### ISSUE TITLE
yas/describe-tables in *scratch* results in "Creating pipe: too many open files"

### ISSUE THREAD

**Issue by whitlockjc** [capitaomorte/yasnippet#550]
Whenever I open Emacs and I'm in the \*scratch\* buffer, if I run `M-x yas/describe-tables` I get the following output on my status line: `Creating pipe: too many open files`.  No new buffer with the list of snippets, or an empty list like you get in \*Messages\*.  Of course, once I change to \*Messages\* or some buffer with a major/minor mode, things work as expected.  I would had expected \*scratch\* to behave just like \*Messages\* with at least an empty snippet list if there were none and not what appears to be an error message.

**Comment by npostavs** [comment]
`yas-describe-tables` works just fine in `*scratch*`.

> Of course, once I change to *Messages* or some buffer with a major/minor mode

Every buffer has a major mode. By default, `*scratch*` is in `lisp-interaction-mode`. Presumably you've changed it in your setup. Please read https://github.com/capitaomorte/yasnippet#important-note-regarding-bug-reporting

**Comment by capitaomorte** [comment]
I've seen the `Creating pipe: too many open files` related to Windows builds of Emacs. But @npostavs is right, please provide a reproducible error recipe and the issue might be reopened for more analysis.

**Comment by whitlockjc** [comment]
I read the linked page prior to submitting this issue although I did neglect to include the Emacs and yasnippets versions, `24.4.4.1` and `20141223.303` respectively, my bad.  That being said, I'm not sure how my recipe was lacking as I explained pretty clearly what the problem was and how to reproduce it.  The only thing I can think of is that I need to be more explicit so here goes:

* Start Emacs without a `~/.emacs`
* Evaluate the proper lines to get yasnippets loaded _(Based on the documentation [here](https://github.com/capitaomorte/yasnippet#important-note-regarding-bug-reporting))_
* `C-x b`
* `*scratch*`
* `RET`
* `M-x`
* `yas/describe-tables`
* `RET`

**Expected**

A representation of the available snippets, which can be an empty list as I mentioned is the case when in the *\*Messages*\* buffer.

**Actual**

An error message: `Creating pipe: too many open files`

Maybe the explicit recipe will be more acceptable but not being able to reproduce does not mean the recipe was lacking.  In case it matters:

* OS version : OS X 10.9.5
* Emacs.app was built by [Emacs for Mac OS X](http://emacsformacosx.com/)

**Comment by capitaomorte** [comment]
> I'm not sure how my recipe was lacking as I explained pretty clearly what the problem was and how to reproduce it. 

You explained the "expected vs actual" pretty clearly, but you missed all the essential rest, which helps us catch the culprit. 

> Maybe the explicit recipe will be more acceptable but not being able to reproduce does not mean the recipe was lacking. 

Yes it does. Yours was a pretty lacking recipe. The best recipe possible is for you to fly us over to your computer and show us the thing live. Since that is probably impossible, the recipe you have now is much better and pretty good: we might start to tell if there really is a problem in yasnippet or if you have little green demons in your scratch buffer. For the yasnippet bug this is the place and we shall spend some of our time investigating, for the latter you need an exorcist. For everything in the middle we can provide some pointers. The clear recipe helps us: I'm sure you can see the difference.

Unfortunately I still can't reproduce this on the very same OSX and Emacs versions. Can you try adding `M-x toggle-debug-on-error` to your recipe before the error appears. You should be greeted with a backtrace once it does. Paste that here please.

**Comment by whitlockjc** [comment]
Explaining basic Emacs commands, like switching buffers, to Emacs module authors didn't seem necessary but now I know.  Sorry for the confusion.  I'll follow your instructions and post anything pertinent.

**Comment by capitaomorte** [comment]
> Explaining basic Emacs commands, like switching buffers, to Emacs module authors didn't seem necessary but now I know.

You either still haven't got it or want to troll us. I hope it's the first: the point of a unambiguous reproduction recipe that we can rule out any interference from other things in your `~/.emacs` and or other steps you might have omitted in the original informal description. Your original recipe just didn't include that information.

**Comment by whitlockjc** [comment]
I'm not trolling, I genuinely just didn't understand.  The recipe was a two step process and I was just surprised at the response I got.  You wanted this, or a more verbose version like in my second post:

* Switch to `*scratch*` buffer
* Execute `yas/describe-tables`

And I felt like I gave you the two steps pretty clearly:

> Whenever I open Emacs and I'm in the *scratch* buffer, if I run `M-x yas/describe-tables` I get the following output on my status line: `Creating pipe: too many open files`.

I was surprised that this wasn't good enough but at least now I know.  Maybe the text form of your hand slapping came off more harsh than intended.  As a fellow open source contributor, I was just surprised  and felt it might help to have a little perspective, from my side.  No big deal.

As to the original issue, I am unable to reproduce in a clean Emacs environment now.  I must have had some gremlins in my environment as I did reboot last night for something unrelated and maybe something got cleared up.

**Comment by npostavs** [comment]
> And I felt like I gave you the two steps pretty clearly

You gave the two steps but it wasn't completely clear that there weren't some *other* hidden steps you performed (especially since doing the same thing on our side causes no problems). You didn't say that you started from `emacs -Q`. When a bug report doesn't state that explicitly it's usually the case that there *is* a `~/.emacs` involved (and quite often causing the problem).

**Comment by capitaomorte** [comment]
@whitlockjc be sure to re-comment if you find the issue again. I'm sorry if my comments sound like hand-slapping, they are not meant to. (which part did you find more harsh? perhaps I can improve it) 

Perhaps the systems you're used to contributing to don't allow (much) programatic user customization, but Emacs sure does, for better or worse. And as @npostavs notes, it is *very often* the case that there is interference from other packages or user customizations. Yasnippet is designed to work with Emacs and whatever "legal" customizations the user has. That's why we insist on complete unambiguous reproduction recipes, otherwise we have to guess, and that is sometimes effort wasted.
