### ISSUE TITLE
Use built in 'warn' instead of custom 'yas--message'

### ISSUE THREAD

**Issue by marcinant** [capitaomorte/yasnippet#572]
Yasnippet is very verbose and prints a lot of unimportant messages to '*Messages*' buffer.

Could you please replace custom 'yas--message' and 'yas-verbosity' which is not easily customizable by user with built in Emacs [warning](http://www.gnu.org/software/emacs/manual/html_node/elisp/Warnings.html) functions such as 'lwarn' and default severity levels.

I could provide PR implementing such changes. Would you accept it?

**Comment by capitaomorte** [comment]
> I could provide PR implementing such changes. Would you accept it?

I would certainly consider it. I I'm curious to see your alternative. This is what `yas-verbosity' is there for. 
I don't understand why that doesn't suit you, but perhaps a concrete proposal would clarify it.

**Comment by marcinant** [comment]
1. messages goes to mini-buffer and '*Messages*' buffer while warnings from 'warn' and 'lwarn' goes to '*Warnings*' and they do not appear in mini-buffer at all.

Personally I don't like to see messages flickering in mini-buffer and I just like to see important warnings or errors in '*Warnings*' buffer. This is the place where developer messages should go.

2. By default :debug warnings are ignored and user (developer) cannot see them unless:
```
(setq-default warning-minimum-log-level :debug)
```
is set. So, there is no need to reinvent wheel with custom functions while everything you need to display warnings with different verbosity levels is already implemented in Emacs and documented pretty well.

3. I'll send PR then and I hope you like it.

**Comment by capitaomorte** [comment]
@marcinant, if you don't want to see messages such as "[yas] exited snippet" in the minibuffer, you have to customize `yas-verbosity`.Because in yasnippet there really are such things as "messages" and "warnings" and they're different. So I wouldn't spend time on the PR if you wish to implement `yas-message` in terms of `lwarn`, `warn` or `display-warning`. 

There is already `yas--warning`, btw the docstring contains a huge typo, it's precisely the other way around.

```elisp
(defun yas--message (level message &rest args)
  "When LEVEL is above `yas-verbosity-level', log MESSAGE and ARGS."
  (when (> yas-verbosity level)
    (message "%s" (apply #'yas--format message args))))

(defun yas--warning (format-control &rest format-args)
  (let ((msg (apply #'format format-control format-args)))
    (display-warning 'yasnippet msg :warning)
    (yas--message 1 msg)))
```

If however, you want to transform **some** `yas--message` calls to `yas--warning` calls, then I'm sure it makes sense for some messages, perhaps even many, but not for every one. 

It has to be analysed on a case by case basis, i.e. I'm open arguments like "this isn't really a message, it's more like a warning, because ...", and "this message isn't very important, let's bump its verbosity threshold". 

Next, if you also want to change `yas--warning` to take behave like `lwarn` (and be implemented in terms of `lwarn`), then that's even better.

**Comment by marcinant** [comment]
First question is how to change code:

1. Change yas--warning to use 'lwarn' instead of 'message' in some cases

or

2. remove 'yas--message' and replace all 'yas--message' calls with 'lwarn'

**Comment by marcinant** [comment]
For example lines 1164 to 1166:
```
    (error (progn
             (yas--message 1 "Error in condition evaluation: %s" (error-message-string err))
             nil))))
```
I would like to change to:
``` 
    (error (progn
             (lwarn '(yas) :error "Error in condition evaluation: %s" (error-message-string err))
             nil))))
```

It would output:
```
Error (yas): Error in condition evaluation: peculiar error
```
in '**Warnings**' buffer.

There is no need for 'yas--message' at all. However it's faster to change 'yas--message' behavior than all 'yas--message' occurrencies.

**Comment by capitaomorte** [comment]
> There is no need for 'yas--message' at all. 

How can that be true? If you replace every `yas--message` call to `lwarn`, you are transforming every message into a warning. And the two are not the same thing. Additionally, if you replace every `yas--message` with `message` you're losing the verbosity control.

So don't get rid of either the `yas--message` abstraction or the `yas--warning` abstractions.

if you, for whatever reason, wish for a simpler system where every bit of user feedback comes through the warning system, Yasnippet, is not that system. If you want to suppress verbosity, Yasnippet comes with a special switch for doing that: `yas-verbosity`.

But, I am willing to turn some `yas--message` calls into `yas--warning` calls. The "error in condition evaluation" example is a good candidate of something that is a message now and could become a warning. Or even an error (we could have to implement `yas--error`).

> However it's faster to change 'yas--message' behavior than all 'yas--message' occurrencies.

This is an added benefit of using abstractions.

**Comment by marcinant** [comment]
Well, message is message and warning is warning.
If we switch all messages which are actually error messages into warnings then we will end with only single level of verbosity and only few messages actually. Then we can use multiple levels of 'lwarn' for debugging and error handling and just plain messages to give some information to user.

**Comment by capitaomorte** [comment]
@marcinant, I see where you're coming from, and I've already said it's true that `yas--message` is being abused for reporting what are actually errors. 

Maybe do the PR for your ideal setup and we'll start from there. 

But some users may want to see more feedback than others, even if it's bening feedback, not a error, a warning, and not debugging information for developers. Some users want to see more stuff appear in the echo area than others. And that's with message and the `yas--message` abstraction.

On a tangent, notice how there's another "duplicated" abstraction in yasnippet. `yas-good-grace' is more or less `debug-on-error`. But I still keep it a separate abstraction because I want to shield yasnippet users from erroneous snippets, which many users rightfully don't view as code but as data. And jumping into the debugger for a data error is unexpected.

I mentioned it also because respecting this abstraction is important if what you're proposing is a redesign of yasnippet's message, warning and error system.

But start from the PR and we'll go from there. Be sure to read CONTRIBUTING.md though.

**Comment by npostavs** [comment]
> Yasnippet is very verbose and prints a lot of unimportant messages to 'Messages' buffer.

Since #683 was merged, yasnippet is a lot less verbose by default.

I think the main problem with switching over to `lwarn`/`display-warning` completely is that it lacks a level between `:debug` and `:warning`. For example `syslog(3)` has LOG_NOTICE, "normal, but significant, condition", and LOG_INFO, "informational message". We could use plain `message` for this level, although that makes it a bit disjoint.

I think there was some talk of a notification system on emacs-devel, but nothing conclusive came out of it, as far as I know.
