### ISSUE TITLE
programmatic way to find/insert snippet?

### ISSUE THREAD

**Issue by fommil** [capitaomorte/yasnippet#595]
I've been using this

```elisp
            (when (eq 0 (buffer-size))
              (insert "head")
              (yas-expand))
```

to insert a template called "head" for my lisp files. It would be really nice if I could do this without having to `insert` text and, further, only if the snippet exists... that way I could automate new file templating across all modes :smile:

Alternative approaches to solve the same problem welcome.

**Comment by capitaomorte** [comment]
Have you seen `yas-expand-snippet`?

**Comment by fommil** [comment]
yes, maybe I didn't understand it but it doesn't seem to take a `string` argument?

**Comment by fommil** [comment]
I mean, it takes the template, not the name of the template.

**Comment by capitaomorte** [comment]
@fommil, yes, it's not great. But that's what I have for you. You can try messing around with implementation details to get to a particular snippet's template, but that would make very brittle code.

I am working on a complete rewrite of the engine in the `snippet-engine` branch, which will make these things trivial. But it's slow progress. Are you interested in contributing?

(but `yas-expand-snippet` does take a `string` argument, one such as `${1:field} $1 mirror`)

**Comment by npostavs** [comment]
I wrote a `yas-expand-snippet-by-name` function at http://emacs.stackexchange.com/a/13901/5296, would it make sense to add to yasnippet?

**Comment by capitaomorte** [comment]
@npostavs, yes. A few points though:

* `yas--all-templates` is affected by `yas-choose-tables-first` and `yas-choose-keys-first` which should be `let`-bound to `nil` so the user isn't prompted like in interactive `yas-expand`. It's also affected by `yas-buffer-local-condition`, which should probably be turned off, but here I'm not so sure.
* the function added should be `yas-lookup-template (name &optional mode noerror)`.  It's easy enough to use with the existing `yas-expand-snippet`. But you can add `yas-expand-snippet-by-name` too if you think it's very useful.
* My idea of the `mode` argument is that, if it is passed, then only the tables for that mode (and perhaps its parents) are used, but `yas--extra-modes` being buffer-local, cannot be used, so `let`-bind it to `nil`. If `mode` is not used, then use `yas--get-snippet-tables` as usual.
* If `noerror` is passed, return nil instead of erroring out. Could be useful to probe for templates.
* You probably will have to make changes to `yas--get-snippet-tables` and `yas--modes-to-activate`, adding optional `mode` arguments there. In `yas--modes-to-activate` it should obviously default to `major-mode`.
* Some docs would be needed, but I promise to write them if you provide the impl. :-)
* Some tests would be nice, but I can write those too.

**Comment by capitaomorte** [comment]
@fommil try out the new trunk and use the new `yas-lookup-snippet` feature. Should do what you want in a simpler fashion.

**Comment by fommil** [comment]
need I say more than the commit I just pushed to my dotfiles :smile: Thanks!!!!

**Comment by fommil** [comment]
aaargh, I'm getting this when trying to use it in `scala-mode` (in which the `scala-mode` is loaded lazily)

```
yas-expand-snippet: [yas] `yas-expand-snippet' needs properly setup `yas-minor-mode'
```

any ideas? I'm calling yas in the `find-file-hook`

**Comment by npostavs** [comment]
I see you called `yas-minor-mode` from many mode hooks, but not in `scala-mode-hook`.

**Comment by fommil** [comment]
got it, I'll do that in my `newfile-template`

Actually the reason I disable yas in scala-mode is because there are a bunch of snippets in the default distribution that are just noise, it also conflicts with the ENSIME completion. Is there any way to disable the noisy completions and always check the ENSIME completion before calling yas? Maybe we need to hand-craft the TAB completer in ENSIME to take yas into account.

**Comment by npostavs** [comment]
You could try something like (untested)

```elisp
(defun reprioritize-minor-modes (important-mode other-mode)
  "Make sure IMPORTANT-MODE's bindings override OTHER-MODE's."
  (let ((entry-needs-promoting
         (assq important-mode
               (cl-member other-mode minor-mode-map-alist :key #'car))))
    (when entry-needs-promoting
      (setq minor-mode-map-alist
            (cons entry-needs-promoting
                  (delq entry-needs-promoting minor-mode-map-alist))))))

(with-eval-after-load 'ensime
  (reprioritize-minor-modes 'ensime-mode 'yas-minor-mode))
```

Also, if you think they aren't very good, consider fixing the scala snippets at https://github.com/AndreaCrotti/yasnippet-snippets
