### ISSUE TITLE
.yas-parents have no effect with web-mode

### ISSUE THREAD

**Issue by jasondf** [capitaomorte/yasnippet#619]
I'm using web-mode and yasnippet for coding PHP and HTML.
To use yasnippet in web-mode, will have to install php-mode, php-auto-yasnippets, emmet-mode and ac-emmet as suggested in [web-mode.org](http://web-mode.org). But I prefer to make it happen just with web-mode and yasnippet.
Part of my web-mode configuration is like this:

     (defadvice yas-expand-from-trigger-key (before web-mode-before-yas-expand activate)
            (run-hooks 'web-mode-cur-language-mode-hook))

     (add-hook 'web-mode-cur-language-mode-hook
      '(lambda ()
         (let ((web-mode-cur-language
                (web-mode-language-at-pos)))
           (if (string= web-mode-cur-language "php")
               (yas-activate-extra-mode 'php-mode)
             (yas-deactivate-extra-mode 'php-mode))
           (if (string= web-mode-cur-language "html")
                (yas-activate-extra-mode 'html-mode)
              (yas-deactivate-extra-mode 'html-mode))
           )))
And following is my yasnippet configuration:

    (add-to-list 'load-path (expand-file-name "elpa/yasnippet" user-emacs-directory))
    (require 'yasnippet)
    (yas-global-mode 1)
It works very well when edit php file in web-mode.

Then open a html file in emacs, input "form" then "tab", everything works fine. But if input "href" then "tab", nothing happened. It supposed to call the "href" snippet in nxml-mode as written in html-mode's .yas-parents.

How could I make this right? I really don't want copy all those snippets from nxml-mode to html-mode.

**Comment by npostavs** [comment]
Should be fixed by #619, can you test it?

**Comment by jasondf** [comment]
Great, it works correctly now, thanks.

**Comment by uu1101** [comment]
Hello,

This seems to have the side-effect that parent's snippets take precedence over the mode's.  For example, I have a "Copyright Notice" snippet bound to `c)` in both `prog-mode` and `sh-mode`, that I use to have the boilerplate inserted.  When expanding `c)` in a `sh-mode` buffer, it inserts the `prog-mode` template, instead of the more specific `sh-mode` one.

In case it is related, `(yas--modes-activate 'sh-mode)` returns the list `prog-mode sh-mode`; this might be the search order used when looking for a matching snippet.

Thank you for your work,
uu1101

**Comment by capitaomorte** [comment]
> In case it is related, (yas--modes-activate 'sh-mode) returns the list prog-mode sh-mode; this might be the search order used when looking for a matching snippet.

Indeed it might, and I think it does. This makes a nice case for a unit test.

**Comment by npostavs** [comment]
hmm, our existing test was explicitly not testing the order, so it didn't occur to me it would be important. I think my change (e56aa6f7b335e34788f479cc5816f4789ed45b9c specifically) produces precisely the opposite order as before, so perhaps this could be fixed by calling `reverse`. Although if we really want more specific modes before parent ones, shouldn't we be doing breadth-1st instead of depth-1st search?

**Comment by capitaomorte** [comment]
> Although if we really want more specific modes before parent ones, shouldn't we be doing breadth-1st instead of depth-1st search?

Perhaps yes. I think we should write the tests first for this one, i.e. figure out exactly what the spec should be. There are four things to think about:

1. Should snippets activated by `yas-activate-extra-mode` shadow the snippets in `major-mode`.
2. Should a mode activated later with `yas-activate-extra-mode` shadow the snippets of modes activated earlier by the same process?
3. Within each category (extra modes and `major-mode`) should snippets of parent modes override snippets of child modes?

My answers would be yes, yes and no. 

If I read you correctly, before e56ee6f 3==no was being respected if only for `major-mode`. Am I right? Were 1==yes and 2==yes also respected?

**Comment by npostavs** [comment]
What about parents of activated modes vs `major-mode`  and parents? Was that number 4?

> If I read you correctly, before e56ee6f 3==no was being respected if only for major-mode. Am I right? Were 1==yes and 2==yes also respected?

I said the order would be opposite from before because I changed from `append`ing sublists into `push`ing items, but looking again at the previous code I realize the `remove-duplicates` complicates things. The docstring doesn't say, but experimenting a bit tells me that the *last* copy is the one that's kept. I think that means the modes end up being topologically sorted? I'm not sure, it's tricky to reason about.

**Comment by capitaomorte** [comment]
> Was that number 4?

Not really, I said 4 above then I could only remember 3 and I forgot to edit.

**Comment by npostavs** [comment]
> Number 4: (subcase of 1) Should parents snippets of activated modes also shadow any snippet in major-mode or major-mode's parents?
> 
> My answer is also "yes" here.

I'm inclined to answer "no" here. If your activated mode happens to derive from `prog-mode` I don't think you'd want `prog-mode` snippets shadowing the `major-mode` snippets.

**Comment by capitaomorte** [comment]
> I'm inclined to answer "no" here. If your activated mode happens to derive from prog-mode I don't think you'd want prog-mode snippets shadowing the major-mode snippets.

Makes perfect sense, I change my vote to no as well.

So now that we have the spec, you say that a breadth-first traversal of a multi-root-tree (the roots being `major-mode` and all the activated modes) respects this spec? If so we should go for it.
