### ISSUE TITLE
Stop shipping snippets for everthing together with the package

### ISSUE THREAD

**Issue by mrkkrp** [capitaomorte/yasnippet#637]
First of all, I usually use either my own snippets or snippets installed as separate packages. And this actually makes sense, people should be able to select what they actually want to use without the need to get a bunch of useless stuff. Separation and modularity.

Most other packages are updated in less than a second. This things takes… I don't know how long, but the fact that I need to *wait* for stuff I will *never* use is killing me.

Most certainly this has been discussed already, but I didn't see any issue about this. Why for the god sake not split all the stuff into separate packages?

Maybe separate recipe on MELPA can be written to exclude all “built-in” snippets?

**Comment by npostavs** [comment]
The snippets are in fact in a separate repository, at https://github.com/AndreaCrotti/yasnippet-snippets. It's included as a submodule of yasnippet.

> Most certainly this has been discussed already, but I didn't see any issue about this. Why for the god sake not split all the stuff into separate packages?

Historically, there was a snippet collection in the main yasnippet repository. So the current situation is an incremental improvement over that. See https://github.com/capitaomorte/yasnippet#where-are-the-snippets

> Maybe separate recipe on MELPA can be written to exclude all “built-in” snippets?

I think it would just be matter of removing `"snippets"` from https://github.com/milkypostman/melpa/blob/master/recipes/yasnippet.

I'm closing, because this is really a packaging issue, not a yasnippet issue.
