### ISSUE TITLE
'Visit snippet file...' barely usable since something change.

### ISSUE THREAD

**Issue by phfrohring** [capitaomorte/yasnippet#655]
Hello!

Yasnippet is great, using it every day :smile: 

Lastly something changed... and it broke my workflow but I guess a lot of workflows :disappointed: .

Here is what happened:

Using `helm`, which is equally great, before some change I could filter snippets in < 2 seconds when visiting them.

Now, I got this :hankey: native menu on osx yosemite:

![screen shot 2016-01-29 at 10 06 48](https://cloud.githubusercontent.com/assets/10885649/12671643/6311b228-c671-11e5-91f2-e6b1f1f8f185.png)

So I guess, this is a bug not really a feature...

Anyway thx again for this great mod!!

Cheers .

**Comment by npostavs** [comment]
Ah, I guess this is the change from #576, that `yas-visit-snippet-file` no longer overrides `yas-prompt-funcions`. You can customize `yas-prompt-functions` yourself to a value that you like better. I think it would make sense to change the default value such that `yas-completing-read` is used by default though, because it respects `completing-read-function` ('m guessing that's how you had a helm prompt before). Also, I don't really like `yas-x-prompt` very much anyway.

**Comment by phfrohring** [comment]
ok thx. Will try to see this this wk!

**Comment by npostavs** [comment]
> I think it would make sense to change the default value such that yas-completing-read is used by default though

See #657.

**Comment by phfrohring** [comment]
:tada:
